CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(256)                     NOT NULL,
    email VARCHAR(128)                         NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY(id),
    CONSTRAINT uq_users_email UNIQUE(email)
);
CREATE TABLE IF NOT EXISTS categories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(128)                 NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS event
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation   VARCHAR(512)                            NOT NULL,
    description  VARCHAR(7000)                           NOT NULL,
    category_id  BIGINT                                  NOT NULL,
    conformed_requests INT                               NOT NULL,
    participant_limit  INT                               NOT NULL,
    user_id            BIGINT                            NOT NULL,
    lat                NUMERIC(8, 5)                     NOT NULL,
    lon                NUMERIC(8, 5)                     NOT NULL,
    created_on         TIMESTAMP                         NOT NULL,
    event_date         TIMESTAMP                         NOT NULL,
    paid               BOOLEAN                           NOT NULL,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN                           NOT NULL,
    state              VARCHAR(64)                       NOT NULL,
    title              VARCHAR(512)                      NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_category_id_events FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_user_id_events FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created    TIMESTAMP DEFAULT now(),
    event_id   BIGINT                          NOT NULL,
    user_id    BIGINT                          NOT NULL,
    status     VARCHAR(64)                     NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_event_id_request FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_user_id_request FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS compilation
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned         BOOLEAN,
    title          VARCHAR(200)                NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS compilation_of_events
(
    comp_id  BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT fk_event_id_compilation_of_events FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_comp_id_compilation_of_events FOREIGN KEY (comp_id) REFERENCES compilation (id)
    );

CREATE TABLE IF NOT EXISTS comments
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_text VARCHAR(512)                            NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    created_on TIMESTAMP DEFAULT  now(),
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_event_id_comment FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_comp_id_comment FOREIGN KEY (user_id) REFERENCES users (id)
);