CREATE TABLE IF NOT EXISTS stats
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(256)                            NOT NULL,
    uri        VARCHAR(512)                            NOT NULL,
    ip         VARCHAR(55)                             NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
    );